### ISSUE TITLE
Questions about simulate-long-reads

### ISSUE THREAD

**Issue by HLHsieh** [BCCDC-PHL/simulate-long-reads#1]
Hello,

I am interested in utilizing this tool, but I have a few questions regarding its functionality:

1. Does the tool support the generation of fast5 files?
2. Which version of Nanopore is it based on?
3. How should I properly cite this tool in my research?

I appreciate your assistance in providing any information.

Best regards,
Hsin

**Comment by dfornika** [comment]
Hi @HLHsieh, sorry I haven't been keeping a close eye on this repo and just saw this issue.

This pipeline is really just a wrapper around Ryan Wick's [Badread](https://github.com/rrwick/Badread) read simulator. It doesn't generate fast5 files, only fastq. Refer to the [Badread paper](https://joss.theoj.org/papers/10.21105/joss.01316) for further details. Whether you use this pipeline or not, please cite the Badread paper. You can cite this GitHub repo if necessary but I may move it to another location and can't guarantee its stability.
